-- +migrate Up
CREATE TABLE IF NOT EXISTS GROUPCHATS (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	user_id INTEGER NOT NULL,
	group_id INTEGER NOT NULL,
	content TEXT NOT NULL,
	created_at DATETIME NOT NULL,
	FOREIGN KEY (user_id) REFERENCES USERS(ID),
    FOREIGN KEY (group_id) REFERENCES GROUPS(ID)
);
