
-- +migrate Up
CREATE TABLE IF NOT EXISTS MENTIONS (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	user_id INTEGER NOT NULL,
	post_id INTEGER NOT NULL,
    mentioned_users TEXT NOT NULL,
	FOREIGN KEY (user_id) REFERENCES USERS(ID),
    FOREIGN KEY (post_id) REFERENCES POSTS(ID)
);
