-- +migrate Up
CREATE TABLE IF NOT EXISTS VOTES (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
    event_id INTEGER NOT NULL,
	user_id INTEGER NOT NULL,
    vote_option TEXT NOT NULL,
    FOREIGN KEY (event_id) REFERENCES EVENTS(ID)
	FOREIGN KEY (user_id) REFERENCES USERS(ID)
);