
-- +migrate Up
CREATE TABLE IF NOT EXISTS PRIVATECHATS (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	sender_id INTEGER NOT NULL,
	recipient_id INTEGER NOT NULL,
    content TEXT,
	created_at DATETIME NOT NULL,
	FOREIGN KEY (sender_id) REFERENCES USERS(ID)
	FOREIGN KEY (recipient_id) REFERENCES USERS(ID)

);