
-- +migrate Up
CREATE TABLE IF NOT EXISTS COMMENTS (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	user_id INTEGER NOT NULL,
    post_id INTEGERN NOT NULL,
	content TEXT NOT NULL,
    image TEXT,
	created_at DATETIME NOT NULL,
	FOREIGN KEY (user_id) REFERENCES USERS(ID)
    FOREIGN KEY (post_id) REFERENCES POSTS(ID)
);