-- +migrate Up
CREATE TABLE IF NOT EXISTS FOLLOWERS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    follower_id INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES USERS(ID),
    FOREIGN KEY (follower_id) REFERENCES USERS(ID)
);
